app/mod_home/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for

import views
from app.mod_library import response
from app.mod_library import router
import validators


# Define the blueprint: 'home', set its url prefix: app.url/auth
mod_home = Blueprint('home', __name__, url_prefix='/')

# Set the route and accepted methods
@mod_home.route('')
def index():
    paginator = views.list_all_company(per_page=int(request.args.get('items', 15)))
    trendings = views.list_trending_companies()
    news = views.list_latest_news()
    watchlist = []
    if 'authenticate' in session:
        watchlist = views.list_of_watchlist(int(request.args.get('witems', 5)), int(request.args.get('wpage', 1))).items
        #from app.mod_database.models import User
        #watchlist = User.auth().favourites
    #    return render_template('company/authenticated_list.html', paginator=paginator, trendings=trendings)
    return render_template('company/list.html', 
            paginator=paginator, news_list=news,
            trendings=trendings, watchlist=watchlist)

@mod_home.route('companies/<company_code>')
@mod_home.route('companies/<company_code>/<slug>')
@mod_home.route('companies/<company_code>/<slug>/')
def company_details(company_code, slug=None):
    company = views.get_only_company(company_code)
    if slug != company.slug:
        return redirect("companies/{}/{}".format(company_code, company.slug))
    company = views.get_current_stock_of_company(company_code, company=company)
    trendings = views.list_trending_companies()
    news = views.list_latest_news()
    watchlist = []
    if 'authenticate' in session:
        watchlist = views.list_of_watchlist().items
    return render_template('company/details.html', 
            company=company, trendings=trendings, 
            news_list=news, watchlist=watchlist)

@mod_home.route('companies/<company_code>/<slug>/stocks')
def company_stock_details(company_code, slug):
    return response.json([company_code, slug, 'stocks'])

@router.api('companies')
def companies():
    #return response.json(views.list_all_company())
    return response.paginate(views.list_all_company())

@router.api('companies/<company_code>/stocks')
def stocks(company_code):
    return response.json(views.get_current_stock_of_company(company_code))

#@router.api('companies/<company_id>/comments', methods=['GET', 'POST'], validator=validators.VAttachment)
@mod_home.route('companies/<company_id>/comments', methods=['POST'])
def comments(company_id):
    if request.method == 'POST':
        #return response.json(views.add_comment_to_company(company_id, request.json))
        data = {
            'comment': request.values.get('comment', None),
            'attachment': request.files.get('attachment', None)
        }
        company = views.add_comment_to_company(company_id, data)
        return redirect('/companies/' + company.code + '/' + company.slug) 
    else:
        return response.paginate(views.list_comments_of_company(company_id))

#@router.api('companies/<company_id>/comments/<comment_id>/reply', methods=['POST'])
@mod_home.route('companies/<company_id>/comments/<comment_id>/reply', methods=['POST'])
def reply(company_id, comment_id):
    if request.method == 'POST':
        company = views.reply_to_comment(company_id, comment_id, request.values.get('replyContent'), request.values.get('replyTo', None))
        print company
        return redirect('/companies/' + company.code + '/' + company.slug) 
    else:
        return response.paginate(views.list_replies_of_comments(company_id, comment_id))

@mod_home.route('companies/<company_id>/watch')
def watch_company(company_id):
    views.add_to_watchlist(company_id)
    return redirect(request.args.get('referer', '/'))

@mod_home.route('companies/<company_id>/unwatch')
def unwatch_company(company_id):
    views.remove_from_watchlist(company_id)
    return redirect(request.args.get('referer', '/'))

@mod_home.route('companies/<company_id>/comments/<comment_id>/like')
def like_comment(company_id, comment_id):
    company = views.like_a_comment(company_id, comment_id)
    details_url = url_for('home.company_details', company_code=company.code, slug=company.slug) 
    return redirect(details_url + '#' + comment_id)

@mod_home.route('companies/<company_id>/comments/<comment_id>/unlike')
def unlike_comment(company_id, comment_id):
    company = views.unlike_a_comment(company_id, comment_id)
    details_url = url_for('home.company_details', company_code=company.code, slug=company.slug) 
    return redirect(details_url + '#' + comment_id)

@router.api('users/watchlist', methods=['GET'])
@router.api('companies/<company_id>/watchlist', methods=['POST', 'DELETE'])
def watchlist(company_id=None):
    if request.method == 'POST':
        return response.json(views.add_to_watchlist(company_id))
    if request.method == 'DELETE':
        return response.json(views.remove_from_watchlist(company_id))
    else:
        return response.paginate(views.list_of_watchlist())

@router.api('companies/filter', methods=['GET'])
def filter():
    return response.json(views.filter(request.args.get('q', None)))
    #return response.paginate(views.filter(request.args.get('q', None)))

@router.api('companies/trending', methods=['GET'])
def trending():
    return response.paginate(views.list_trending_companies())

#@router.api('login', methods=['POST'], validator=validators.VLogin)
@mod_home.route('login', methods=['POST'])
def login():
    """
    request.args
    request.form
    request.files
    request.values
    request.json
    """
    #print request.values
    user = views.login_user(request.values)
    return response.redirect()

@router.api('login/google', methods=['GET'])
def google_login():
    return views.google_login_user(request.args.get('code'))

#@router.api('user/logout', methods=['GET'])
@mod_home.route('user/logout', methods=['GET'])
def logout():
    views.logout_user()
    return response.redirect()

#@router.api('users', methods=['POST'])
#def signup():
#    return views.signup_user(request.json)

@mod_home.route('user/signup', methods=['POST'])
def user_signup():
    views.signup_user(request.form)
    return response.redirect()

app/templates/company/macros/_commentform.html
{% macro commentform(company) %}

{% if 'authenticate' not in session %}
<div class="row col-12 m-0 p-0">
    <div name="coment-form" class="col-12">
        <div class="form-group">
            <label for="anonymous-comment" class="py-2">
                <img src="{{ url_for('static', filename='img/logo.png') }}" height="30" width="30" />
                <b class="pl-2">Anonymous</b>
            </label>
            <textarea class="form-control" id="anonymous-comment" rows="3"></textarea>
        </div>
        <div class="d-flex justify-content-end">
            <button class="btn btn-md btn-primary" data-toggle="modal" data-target="#login">POST</button>
        </div>
    </div>
</div>
{% else %}
<div class="row m-0 p-2 col-12">
    <form name="comment-form-person" action="/companies/{{ company.id }}/comments" method="POST" class="col-12 p-0" enctype="multipart/form-data">
        <div class="form-group">
            <label for="anonymous-comment-person" class="py-2" style="display: inline-flex;">
                <div class="name-image">
                    <span>{{ session['authenticate'].user.name[0] }}</span>
                </div>
                <span class="pl-2 fw-500">{{ session['authenticate'].user.name }}</span>
            </label>
            <textarea class="form-control" id="comment-person" name="comment" rows="3" placeholder="Share your view about company"></textarea>
        </div>
        <div class="form-group">
            <input type="file" class="form-control-file float-left" name="attachment" id="upload-file-person">
            <!-- <img class="float-left" src="{{url_for('static',filename='img/Spinner.svg')}}"> -->
            <button type="submit" class="btn btn-sm btn-primary float-right">POST</button>
        </div>
    </form>
</div>
{% endif %}

{% endmacro %}

app/templates/company/macros/_commentlist.html
{% macro commentlist(company, comments) %}
{% for comment in comments %}
<div class="media p-2 col-12 parent-comment">
    <div class="mr-3 name-image">{{ comment.user.name[0] }}</div>
    <div class="media-body">
        <div class="row m-0 p-0">
            <h6 class="my-1">{{ comment.user.name }}</h6>
            <div class="pl-2">
                <small>{{ comment.createdAt|timesince('Just Now') }}</small>
            </div>
        </div>
        <p class="m-0">{{ comment.message }}</p>
        {% if comment._attachment %}
        <img class="comment-image" src="{{ comment._attachment.selfLink }}" alt="http://www.excel-easy.com/examples/images/bar-chart/bar-chart.png" width="100%" />
        {% endif %}
        <div class="row m-0 p-2">
            <ul class="comment_options">
                <li class="my-auto">
                    <span class="f-14 fw-500">{{ comment.likes_count|counts('like', 'likes') }}</span>
                </li>
                <li class="custom-li" title="like">
                    {% if 'authenticate' in session %}
                        {% if comment.like(session['authenticate'].user._id) %}
                        <a href="{{ url_for('home.unlike_comment', company_id=company.id, comment_id=comment.id) }}" >
                            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        </a>
                        {% else %}
                        <a href="{{ url_for('home.like_comment', company_id=company.id, comment_id=comment.id) }}" >
                            <i class="fa fa-thumbs-o-up" style="color:grey;" aria-hidden="true"></i>
                        </a>
                        {% endif %}
                    {% else %}
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                    {% endif %}
                </li>
                <li class="my-auto">
                    {% set replyCount = comment.replies|length %}
                    <span class="f-14 fw-500">{{ replyCount }} {% if replyCount > 1 %} replies {% else %}reply{% endif %}</span>
                </li>
                <li class="custom-li" title="View Reply">
                    <a href="#commentReply{{ loop.index }}" data-toggle="collapse" aria-expanded="false" aria-controls="commentReply{{ loop.index }}">
                        <i class="fa fa-comments black-color"></i>
                    </a>
                </li>

                <li class="custom-li" title="Reply">
                    <a href="#collapseReplyform{{ loop.index }}" data-toggle="collapse" aria-expanded="false" aria-controls="collapseReplyform{{ loop.index }}">
                        <i class="fa fa-reply black-color"></i>
                    </a>
                </li>
                
            </ul>
            <!-- <small class="ml-auto">3 likes</small> -->
        </div>
        <div id="collapseReplyform{{ loop.index }}" class="collapse">
            <form class="col-12 form-inline" name="reply" method="POST" action="{{ url_for('home.reply', company_id=company.id, comment_id=comment.id) }}">
                <div class="form-group w-100">
                    <textarea class="col-10 form-control" rows="2" name="replyContent"></textarea>
                    <div class="col-2">
                        <button class="btn btn-info btn-sm">reply</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="row w-100 m-100 collapse" id="commentReply{{ loop.index }}">
            {% if comment.replies|length > 0 %}
            {% for reply in comment.replies %}
            <div class="media p-2 ml-3 child-media w-100" >
                <div class="mr-1 name-image">{{ reply.user.name[0] }}</div>
                <div class="media-body">
                    <div class="row m-0 p-1">
                        <h6 class="mt-0">{{ reply.user.name }}</h6>
                        <div class="ml-auto">
                            <small>{{ reply.createdAt|timesince('Just Now') }}</small>
                        </div>
                    </div>
                    <p>{{ reply.message }}</p>
                </div>
            </div>
            {% endfor %}
            {% else %}
                <div class="media p-2 m-3 child-media w-100" >
                 No replies
                </div>
            {% endif %}
        </div>
    </div>
</div>
<hr class="w-100 m-0"/>
{% endfor %} 
{% endmacro %}

app/templates/company/macros/_navbar.html
{% macro navbar() %}

<header class="navbar navbar-expand-lg sticky-top fixed-top">
    <a class="navbar-brand" href="/">
                <img src="{{ url_for('static', filename='img/logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
                NoodleStocks
            </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
        <i class="fa fa-bars" aria-hidden="true"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="search ml-auto">
            <input class="Typeahead-input tt-input" id="demo-input" type="text" name="q" placeholder="Search for Companies..." autocomplete="off" spellcheck="false" dir="auto">
        </div>
        <ul class="navbar-nav ml-auto">
            {% if not session['authenticate'] %}
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#login">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#signup">Signup</a>
            </li>
            {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ session['authenticate'].user.name }}
                    </a>
                <div class="dropdown-menu  dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a href="/user/logout?referer={{current_url()}}" class="dropdown-item" style="color: #283593;cursor: pointer;">Logout</a>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>
</header>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <ul class=flashes>
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}

<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModal">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/login?referer={{current_url()}}" method="POST" class="login-form" name="loginform">
                    <div class="form-group">
                        <label for="loginEmail">Email address</label>
                        <input type="email" class="form-control" id="loginEmail" placeholder="Enter email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="loginPassword">Password</label>
                        <input type="password" class="form-control" id="loginPassword" name="password" placeholder="Password" />
                    </div>
                    <div class="login-signup-modal py-2">Don't have account, Please signup.</div>
                    <button type="submit" class="btn btn-primary">login</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signupModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="/user/signup?referer={{current_url()}}"  method="POST" class="submit-form" name="submitform">
                <div class="modal-header">
                    <h5 class="modal-title" id="signupModal">Signup</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="signupUsername">Username</label>
                        <input type="text" name="name" class="form-control" id="signupUsername" aria-describedby="emailHelp" placeholder="Enter username">
                    </div>
                    <div class="form-group">
                        <label for="signupEmail">Email address</label>
                        <input type="email" class="form-control" id="signupEmail" aria-describedby="emailHelp" placeholder="Enter email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="signupPassword1">Password</label>
                        <input type="password" class="form-control" id="signupPassword1" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label for="signupPassword2">Confirm Password</label>
                        <input type="password" class="form-control" id="signupPassword2" name="confirmPassword" placeholder="Password">
                    </div>
                    <div class="signup-login-modal py-2">Already have account, Please login.</div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" ng-click="">Signup</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endmacro %}

app/templates/company/macros/_news.html
{% macro latest_news(news_list) %}

<div class="list-group col-12 px-2">
    {% for news in news_list %}
    <a href="{{ news.url }}" target="_blank" class="list-group-item list-group-item-action p-1">
        <div class="row m-0 bb-1">
            <div class="col-3 pl-2">
                <img src="{{ news.image or '/static/img/no_image.svg' }}" height="auto" width="100%">
            </div>
            <div class="col-9 p-0">
                <p class="mb-1 fw-500 f-14">{{ news.title }}</p>
                <small>{{ news.publishedAt|to_datetime|timesince }}</small>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

{% endmacro %}

app/templates/company/macros/_pagination.html
{% macro paginate(paginator, items_label='items', pageno_label='page') %}

<nav aria-label="Page navigation example" class="mt-3">
    <ul class="pagination justify-content-center">
        {% if paginator.has_prev %}
            {% set query_params = {items_label: paginator.per_page, pageno_label: paginator.page - 1} %}
            <li class="page-item"><a href="{{ current_url(**query_params) }}" class="page-link"><i class="fa fa-chevron-left"></i></a></li>
        {% endif %}
        {% for p in paginator.iter_pages() %}
            {% if p == None %}
                <li class="page-item"><a class="page-link" href="javascript:void(0)">. . .</a></li>
            {% else %}
                {% if p == paginator.page %}
                    <li class="active page-item">
                        <a class="page-link" href="javascript::void(0)">{{ p }}</a>
                    </li>
                {% else %}
                    {% set query_params = {items_label: paginator.per_page, pageno_label: p} %}
                    <li class="page-item"><a class="page-link" href="{{ current_url(**query_params) }}">{{ p }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if paginator.has_next %}
            {% set query_params = {items_label: paginator.per_page, pageno_label: paginator.page + 1} %}
            <li class="page-item"><a class="page-link" href="{{ current_url(**query_params) }}"><i class="fa fa-chevron-right"></i></a></li>
        {% endif %}
    </ul>
</nav>    

{% endmacro %}

app/templates/company/macros/_trending.html
{% macro trending(companies) %}

<div class="col-12 left-side-box p-3">
    <div class="d-flex left-side-box-header">
        <i class="fa fa-line-chart" aria-hidden="true"></i>
        <span>Trending</span>
    </div>
    <hr class="m-2">
    <div class="d-flex row m-0">
        {% for t_company in companies %}
        {% set t_stock = t_company.stock %}
        {% set t_stock_change = (t_stock.last|float - t_stock.close|float) %}
        {% set t_stock_change_percentage = (100 * (t_stock_change / t_stock.last|float))|round(2, 'floor') %}
        <div class="treding-item p-0 m-1 col-12 f-13
        {% if t_stock.last < t_stock.open %}red-sm-border{% else %}green-sm-border{% endif %}" data-src="/companies/{{t_company.code}}">
            <span class="fw-500">{{ t_company.code }}</span>
            <span class="{% if t_stock.last < t_stock.open %}red{% else %}green{% endif %}">{{ t_stock.last }}</span>
            <span class="float-right">({{ t_stock_change }})&nbsp; {{ t_stock_change_percentage }}% &nbsp;</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endmacro %}

app/templates/company/macros/_watchlist.html
{% macro watchlist(companies) %}

<div class="col-12 left-side-box p-3">
    <div class="d-flex left-side-box-header">
        <i class="fa fa-bar-chart" aria-hidden="true"></i>
        <span>Watchlist</span>
    </div>
    <hr class="m-2">
    {% if 'authenticate' not in session %}
    <div class="row m-0">
        <small>Sign up with NoodleStocks to have watchlist for easy access to your favorite stocks.</small>
        <button type="button" class="btn btn-primary btn-sm mx-auto" data-toggle="modal" data-target="#signup">Sign up</button>
    </div>
    {% else %}
    <div class="d-flex row m-0">
        {% if not companies|length %}
        <p style="color: grey;">You are not watching any company.</p>
        {% endif %}
        {% for w_company in companies %}
        {% set w_stock = w_company.stock %}
        {% set w_stock_change = (w_stock.last|float - w_stock.close|float) %}
        {% set w_stock_change_percentage = (100 * (w_stock_change / w_stock.last|float))|round(2, 'floor')  %}
        <div class="treding-item p-0 m-1 col-12 
            {% if w_stock.close < w_stock.open %}red-sm-border{% else %}green-sm-border{% endif %}" data-src="/companies/{{w_company.code}}">
            <span>{{ w_company.code }}</span>
            <span>{{ w_company.close }}</span>
            <span class="float-right">({{ w_stock_change }})&nbsp; {{ w_stock_change_percentage }}% &nbsp;</span>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endmacro %}