app/mod_home/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for

import views
from app.mod_library import response
from app.mod_library import router
import validators


# Define the blueprint: 'home', set its url prefix: app.url/auth
mod_home = Blueprint('home', __name__, url_prefix='/')

# Set the route and accepted methods
@mod_home.route('')
def index():
    paginator = views.list_all_company(per_page=int(request.args.get('items', 15)))
    trendings = views.list_trending_companies()
    news = views.list_latest_news()
    watchlist = []
    if 'authenticate' in session:
        watchlist = views.list_of_watchlist(int(request.args.get('witems', 5)), int(request.args.get('wpage', 1))).items
        #from app.mod_database.models import User
        #watchlist = User.auth().favourites
    #    return render_template('company/authenticated_list.html', paginator=paginator, trendings=trendings)
    return render_template('company/list.html', 
            paginator=paginator, news_list=news,
            trendings=trendings, watchlist=watchlist)

@mod_home.route('companies/<company_code>')
@mod_home.route('companies/<company_code>/<slug>')
@mod_home.route('companies/<company_code>/<slug>/')
def company_details(company_code, slug=None):
    company = views.get_only_company(company_code)
    if slug != company.slug:
        return redirect("companies/{}/{}".format(company_code, company.slug))
    company = views.get_current_stock_of_company(company_code, company=company)
    trendings = views.list_trending_companies()
    news = views.list_latest_news()
    watchlist = []
    if 'authenticate' in session:
        watchlist = views.list_of_watchlist().items
    return render_template('company/details.html', 
            company=company, trendings=trendings, 
            news_list=news, watchlist=watchlist)

@mod_home.route('companies/<company_code>/<slug>/stocks')
def company_stock_details(company_code, slug):
    return response.json([company_code, slug, 'stocks'])

@router.api('companies')
def companies():
    #return response.json(views.list_all_company())
    return response.paginate(views.list_all_company())

@router.api('companies/<company_code>/stocks')
def stocks(company_code):
    return response.json(views.get_current_stock_of_company(company_code))

#@router.api('companies/<company_id>/comments', methods=['GET', 'POST'], validator=validators.VAttachment)
@mod_home.route('companies/<company_id>/comments', methods=['POST'])
def comments(company_id):
    if request.method == 'POST':
        #return response.json(views.add_comment_to_company(company_id, request.json))
        data = {
            'comment': request.values.get('comment', None),
            'attachment': request.files.get('attachment', None)
        }
        company = views.add_comment_to_company(company_id, data)
        return redirect('/companies/' + company.code + '/' + company.slug) 
    else:
        return response.paginate(views.list_comments_of_company(company_id))

#@router.api('companies/<company_id>/comments/<comment_id>/reply', methods=['POST'])
@mod_home.route('companies/<company_id>/comments/<comment_id>/reply', methods=['POST'])
def reply(company_id, comment_id):
    if request.method == 'POST':
        company = views.reply_to_comment(company_id, comment_id, request.values.get('replyContent'), request.values.get('replyTo', None))
        print company
        return redirect('/companies/' + company.code + '/' + company.slug) 
    else:
        return response.paginate(views.list_replies_of_comments(company_id, comment_id))

@mod_home.route('companies/<company_id>/watch')
def watch_company(company_id):
    views.add_to_watchlist(company_id)
    return redirect(request.args.get('referer', '/'))

@mod_home.route('companies/<company_id>/unwatch')
def unwatch_company(company_id):
    views.remove_from_watchlist(company_id)
    return redirect(request.args.get('referer', '/'))

@mod_home.route('companies/<company_id>/comments/<comment_id>/like')
def like_comment(company_id, comment_id):
    company = views.like_a_comment(company_id, comment_id)
    details_url = url_for('home.company_details', company_code=company.code, slug=company.slug) 
    return redirect(details_url + '#' + comment_id)

@mod_home.route('companies/<company_id>/comments/<comment_id>/unlike')
def unlike_comment(company_id, comment_id):
    company = views.unlike_a_comment(company_id, comment_id)
    details_url = url_for('home.company_details', company_code=company.code, slug=company.slug) 
    return redirect(details_url + '#' + comment_id)

@router.api('users/watchlist', methods=['GET'])
@router.api('companies/<company_id>/watchlist', methods=['POST', 'DELETE'])
def watchlist(company_id=None):
    if request.method == 'POST':
        return response.json(views.add_to_watchlist(company_id))
    if request.method == 'DELETE':
        return response.json(views.remove_from_watchlist(company_id))
    else:
        return response.paginate(views.list_of_watchlist())

@router.api('companies/filter', methods=['GET'])
def filter():
    return response.json(views.filter(request.args.get('q', None)))
    #return response.paginate(views.filter(request.args.get('q', None)))

@router.api('companies/trending', methods=['GET'])
def trending():
    return response.paginate(views.list_trending_companies())

#@router.api('login', methods=['POST'], validator=validators.VLogin)
@mod_home.route('login', methods=['POST'])
def login():
    """
    request.args
    request.form
    request.files
    request.values
    request.json
    """
    #print request.values
    user = views.login_user(request.values)
    return response.redirect()

@router.api('login/google', methods=['GET'])
def google_login():
    return views.google_login_user(request.args.get('code'))

#@router.api('user/logout', methods=['GET'])
@mod_home.route('user/logout', methods=['GET'])
def logout():
    views.logout_user()
    return response.redirect()

#@router.api('users', methods=['POST'])
#def signup():
#    return views.signup_user(request.json)

@mod_home.route('user/signup', methods=['POST'])
def user_signup():
    views.signup_user(request.form)
    return response.redirect()

app/templates/company/base.html
<!DOCTYPE html>
<html>

<head>
    <base href="/"></base>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="format-detection" content="telephone=no" />
    {% block meta %}
    <meta name="description" content="NoodleStock provides the latest stock market, financial and business news. Learn from other stock traders and get new ideas.">
    <meta name="keywords" content="stock, noodlestock, stock conversations, stock trends, financial trends, stocks, trade, trading, shares, financial forum, financial advice, financial conversation,  financial news, stock forum, stock advice, stock conversation, trending stock, latest stock,Live Stock Markets, Live Stock Price, Stock Trading news, Share Market, Views and Analysis on Equity and Stock Markets Tips, sensex, nifty, Commodity Market, personal finance, mutual funds, insurance, bank and loans.">
    {% endblock %}
    <meta name="author" content="NoodleStock">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
    <title>{% block title %}NoodleStocks {% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='img/logo.png') }}" sizes="32x32">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-v4.0.0-beta.2.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/font-awesome.min.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}"/>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
</head>

<body>

    {% block body %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script> -->
    <script type="text/javascript" src="{{url_for('static',filename='js/typeahead.js')}}"></script>
    <script>
       window.onload = function() {
            try{
                (adsbygoogle = window.adsbygoogle || []).push({});
            }
            catch(e){

            }
        }
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-26826257-6"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-26826257-6');
    </script>
</body>

</html>

app/templates/company/list.html
{% from "company/macros/_trending.html" import trending with context %}
{% from "company/macros/_watchlist.html" import watchlist as watchlist_macro with context %}
{% from "company/macros/_navbar.html" import navbar with context %}
{% from "company/macros/_pagination.html" import paginate with context %}
{% from "company/macros/_news.html" import latest_news with context %}
{% extends "company/base.html" %}

{% block title %} Noodlestock - Get realtime shares, stocks information, news & Discuss about investment - noodlestock.com {% endblock %}

{% block body %}
    
    {{ navbar() }}

    <div class="container-fluid list-container">
        <div class="row m-0">
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
                {{ trending(trendings) }}
                {{ watchlist_macro(watchlist)}}
                <!-- <div class="ads-block col-12 p-2">
                    <ins class="adsbygoogle" style="display:block;width:100%;" data-ad-client="ca-pub-0503054612740442" data-ad-slot="2418973612" data-ad-format="auto" target="_newTab"></ins>
                </div>
                <div class="col-12 left-side-box p-3">
                    <div class="left-side-box-header clearfix">
                        <i class="fa fa-newspaper-o float-left" aria-hidden="true"></i>
                        <span class="float-left">Latest News</span>
                        <a class="float-right view-more">view more</a>
                    </div>
                    <hr class="m-2">
                    <div class="d-flex row m-0">
                        {{ latest_news(news_list) }}
                    </div>
                </div> -->
                <!-- <div class="ads-block col-12 p-0">
                    <ins class="adsbygoogle" style="display:block;width:100%;" data-ad-client="ca-pub-0503054612740442" data-ad-slot="2418973612" data-ad-format="auto" target="_newTab"></ins>
                </div> -->
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="middle-box col-12 p-3">
                    <div class="list-group feed-list-group">
                        {% for company in paginator.items %}
                        <div class="m-list list-group-item stock-item clearfix" data-src="/companies/{{company.code}}/{{company.name}}">
                            {% set stock = company.stock %}
                            {% set stock_change = (stock.last|float - stock.close|float) %}
                            {% set stock_change_percentage = (100 * (stock_change / stock.last|float))|round(2, 'floor') %}
                            <div class="pull-left company-list {% if stock.last|float < stock.close|float %}border-list-red{% else %}border-list-green{% endif %}">
                                <div class="company-name">{{ company.name }}</div>
                                <div class="company-data">
                                    <span class="company-code">{{ company.code }}</span>
                                    <span class="current">{{ stock.close }}</span>
                                    {% if stock.last|float < stock.close|float %}
                                    <span class="up-down-arrow "><i class="fa fa-arrow-down red"></i></span>
                                    {% else %}
                                    <span class="up-down-arrow "><i class="fa fa-arrow-up green"></i></span>
                                    {% endif %}
                                    <span class="stock status">{{ stock_change }}
                                        &nbsp; ({{ stock_change_percentage }}%) &nbsp;</span>
                                </div>
                                <!-- <div class="updated-at">
                                    <small>Updated on {#{ company.refreshedAt.strftime('%a, %b %d, %Y %I:%M %p') }#}</small>
                                </div> -->
                            </div>
                            <div class="pull-right">
                                <!-- <div class="watchers"> -->
                                {% if not session['authenticate'] %}
                                <span style="font-size:12px;color:grey;">{{ company.watchlistcount }} follower</span>
                                    <i class="fa fa-star unactive-watcher" onclick="openLoginModal(event)" ></i>
                                {% else %}
                                    <span style="font-size:12px;color:grey;">{{ company.watchlistcount }} follower</span>
                                    {% if company not in watchlist %}
                                    <a href="{{ url_for('home.watch_company', company_id=company.id, referer=request.url) }}" title="Add to watchlist">
                                        <!-- <button type="button" class="btn btn-sm btn-primary pull-right">Watch</button> -->
                                        <i class="fa fa-star unactive-watcher"></i>
                                    </a>
                                    {% else %}
                                    <a href="{{ url_for('home.unwatch_company', company_id=company.id, referer=request.url) }}" title="Remove from watchlist">
                                        <!-- <button type="button" class="btn btn-sm btn-danger pull-right">Remove Watch</button> -->
                                        <i class="fa fa-star active-watcher"></i>
                                    </a>
                                    {% endif %}
                                {% endif %}    
                            </div>
                        </div>
                        {% endfor %}
                        {{ paginate(paginator) }}
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
                <div class="col-12 left-side-box p-3">
                    <div class="left-side-box-header clearfix">
                        <i class="fa fa-newspaper-o float-left" aria-hidden="true"></i>
                        <span class="float-left">Latest News</span>
                        <a class="float-right view-more">view more</a>
                    </div>
                    <hr class="m-2">
                    <div class="d-flex row m-0">
                        {{ latest_news(news_list) }}
                    </div>
                </div> 
                <div class="ads-block col-12 p-0">
                    <ins class="adsbygoogle" style="display:block;width:100%;" data-ad-client="ca-pub-0503054612740442" data-ad-slot="2418973612" data-ad-format="auto" target="_newTab"></ins>
                </div>
            </div>
        </div>
    </div>
{% endblock %}